
exports.SlashCommands = [
	{ "name": "amber", "description": "🐈 View some Amber cat photos!" },
	{ "name": "aww", "description": "🤗 Posts from r/aww" },
	{ "name": "bird", "description": "🐦 View some birds!" },
	{ "name": "bunny", "description": "🐇 View some bunnies!" },
	{ "name": "cat", "description": "🐈 View some cats!" },
	{ "name": "chase", "description": "🐕 View some Chase dog photos!" },
	{ "name": "dog", "description": "🐕 View some dogs!" },
	{ "name": "duck", "description": "🦆 View some ducks! QUACK!" },
	{ "name": "fox", "description": "🦊 View some foxes!" },
	{ "name": "husky", "description": "🐕 View some huskies!" },
	{ "name": "invite", "description": "Invite me to your server!" },
	{ "name": "koala", "description": "🐨 View some Koala photos!" },
	{ "name": "mischief", "description": "🐈 View some Mischief cat photos!" },
	{ "name": "ollie", "description": "🐈 View some Ollie cat photos!" },
	{ "name": "otter", "description": "🦦 View some otters!" },
	{ "name": "panda", "description": "🐈 View some Panda cat photos!" },
	{ "name": "pandas", "description": "🐼 View some pandas!" },
	{ "name": "penguin", "description": "🐧 View some penguins!" },
	{ "name": "pj", "description": "🐈 View some PJ cat photos!" },
	{ "name": "pug", "description": "🐕 View some pugs!" },
	{ "name": "raccoon", "description": "🦝 View some Raccoon photos!" },
	{ "name": "redpanda", "description": "View some red pandas!" },
	{ "name": "shibe", "description": "🐕 View some shibes!" },
	{ "name": "sylvester", "description": "🐈 View some Sylvester cat photos!" },
	{ "name": "tiggy", "description": "🐈 View some Tiggy cat photos!" }
]